(()=>{
'use strict';
const root=document.documentElement, menu=document.querySelector('.menu-button'), nav=document.querySelector('#navigation');
const closeMenu=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Мәзірді ашу');};
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Мәзірді жабу':'Мәзірді ашу');});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeMenu();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
const wide=matchMedia('(min-width:901px)');wide.addEventListener('change',e=>{if(e.matches)closeMenu();});
const reduced=matchMedia('(prefers-reduced-motion: reduce)'), motionButton=document.querySelector('.motion-toggle');
let paused=false;try{paused=localStorage.getItem('tilek-motion-paused')==='true';}catch{}
const updateMotion=()=>{const off=paused||reduced.matches;root.classList.toggle('motion-paused',off);motionButton.setAttribute('aria-pressed',String(off));motionButton.disabled=reduced.matches;motionButton.setAttribute('aria-label',reduced.matches?'Құрылғыңызда қозғалысты азайту қосылған':(off?'Анимацияны қосу':'Анимацияны тоқтату'));motionButton.title=reduced.matches?'Құрылғыңызда қозғалысты азайту қосылған':(off?'Анимацияны қосу':'Анимацияны тоқтату');motionButton.querySelector('span').textContent=off?'▷':'Ⅱ';document.querySelectorAll('.tilt').forEach(el=>{el.style.removeProperty('--rx');el.style.removeProperty('--ry');});if(off)document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));};
motionButton.addEventListener('click',()=>{paused=!paused;try{localStorage.setItem('tilek-motion-paused',String(paused));}catch{}updateMotion();});reduced.addEventListener('change',updateMotion);updateMotion();
if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');io.unobserve(entry.target);}});},{threshold:.08,rootMargin:'0px 0px -15px 0px'});document.querySelectorAll('.reveal').forEach(el=>{el.classList.add('pending');io.observe(el);});}
if(matchMedia('(hover:hover) and (pointer:fine)').matches){document.querySelectorAll('.tilt').forEach(el=>{el.addEventListener('pointermove',e=>{if(root.classList.contains('motion-paused'))return;const b=el.getBoundingClientRect();el.style.setProperty('--ry',((e.clientX-b.left)/b.width-.5)*4+'deg');el.style.setProperty('--rx',-((e.clientY-b.top)/b.height-.5)*3+'deg');});el.addEventListener('pointerleave',()=>{el.style.setProperty('--rx','0deg');el.style.setProperty('--ry','0deg');});});}
let scrollScheduled=false;const progress=document.querySelector('.scroll-progress');const updateProgress=()=>{const length=root.scrollHeight-innerHeight;progress.style.width=(length>0?Math.min(100,scrollY/length*100):0)+'%';scrollScheduled=false;};addEventListener('scroll',()=>{if(!scrollScheduled){requestAnimationFrame(updateProgress);scrollScheduled=true;}},{passive:true});addEventListener('resize',updateProgress);updateProgress();
const run=document.querySelector('#run-code');if(run)run.addEventListener('click',()=>{const out=document.querySelector('#code-output');out.hidden=!out.hidden;run.textContent=out.hidden?'Мысалды көрсету ▷':'Нәтижені жасыру ↑';run.setAttribute('aria-expanded',String(!out.hidden));});
const hardware={cpu:['Процессор','Бағдарлама нұсқауларын орындайды және есептеулер жүргізеді. Оның мүмкіндігі компьютердің көптеген тапсырмаларды орындауына әсер етеді.'],gpu:['Видеокарта','Кескін мен графиканы өңдейді. Ойындардағы графика мен бейнелерді экранға шығаруға қатысады.'],ram:['Жедел жад','Қазір қолданылып жатқан бағдарламалардың деректерін уақытша сақтайды. Қуат өшкенде оның ішіндегі деректер сақталмайды.']};
const tabs=[...document.querySelectorAll('[data-hardware]')];const selectTab=tab=>{tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});const panel=document.querySelector('#panel-hardware'),data=hardware[tab.dataset.hardware];panel.setAttribute('aria-labelledby',tab.id);panel.querySelector('h3').textContent=data[0];panel.querySelector('p').textContent=data[1];};tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;if(e.key==='Home')j=0;if(e.key==='End')j=tabs.length-1;if(j!==undefined){e.preventDefault();selectTab(tabs[j]);tabs[j].focus();}});});
const gallery=[...document.querySelectorAll('[data-photo]')],dialog=document.querySelector('#lightbox');let selected=0,returnFocus=null;
if(dialog){const show=index=>{selected=(index+gallery.length)%gallery.length;const b=gallery[selected],img=document.querySelector('#lightbox-image');img.src=b.dataset.photo;img.alt=b.querySelector('img').alt;document.querySelector('#lightbox-caption').textContent=b.dataset.caption;document.querySelector('#lightbox-count').textContent=`${selected+1} / ${gallery.length}`;};gallery.forEach((b,i)=>b.addEventListener('click',()=>{returnFocus=b;show(i);dialog.showModal();document.body.style.overflow='hidden';}));dialog.querySelector('.lightbox-close').addEventListener('click',()=>dialog.close());dialog.querySelector('.lightbox-prev').addEventListener('click',()=>show(selected-1));dialog.querySelector('.lightbox-next').addEventListener('click',()=>show(selected+1));dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();show(selected+1);}if(e.key==='ArrowLeft'){e.preventDefault();show(selected-1);}});dialog.addEventListener('close',()=>{document.body.style.overflow='';returnFocus?.focus();});}
})();
